import re

with open('index_en.html', 'r', encoding='utf-8') as f:
    html = f.read()

# Replace all remaining Chinese paragraphs with English using regex or simple string replacement.
repls = {
    '''1947年爆發的二二八事件，其表面上的導火線雖為''': '''Although the apparent trigger of the 228 Incident that erupted in 1947''',
    '''反對政治壟斷」與「對抗腐敗貪污」。''': '''opposed political monopoly," and "fought against corruption." ''',

    # Chapter 3
    '''在當前的數位認知作戰中，除了宏觀數據的爭辯外，攻擊者亦經常透過放大檢視特定歷史個案，藉此質疑《二二八事件處理及賠償條例》的發放標準存在政治偏見與族群歧視。其中，專欄作家張若彤所提出的「劉青山案」與「何鑾旗案」之對比，便是近期網路上被廣泛引用，用以指控官方「淡化歷史」、「選擇性給予正義」的典型案例。要釐清此類指控，必須深入探討轉型正義的法理基礎與法律要件。''': '''In the current digital cognitive warfare, in addition to debates over macro data, attackers frequently zoom in on specific historical cases to question whether the "228 Incident Disposition and Compensation Act" payment standards harbor political bias and ethnic discrimination. Among them, the contrast between the "Liu Qing-shan Case" and the "He Luan-qi Case" raised by columnist Chang Jo-tung is a typical example widely cited online recently to accuse officials of "downplaying history" and "selectively dispensing justice." To clarify such allegations, we must delve into the jurisprudential foundation and legal elements of transitional justice.''',

    '''劉青山為二二八事件期間任職於專賣局台中分局的一名28歲外省籍公務員。1947年3月2日，當憤怒的台中群眾包圍前台中縣長劉存忠官邸進行抗議時，劉青山自屋內衝出並向群眾開槍，導致數名抗議民眾受傷。此舉引發群眾極度憤慨，隨即將其包圍並嚴重毆打。根據部分官方檔案（如專賣局的二二八專刊）及見證者記錄，劉青山被送醫急救後，甚至有暴民在3月3日夜間衝入醫院病房，將其割去耳鼻、挖出雙眼，最終殘忍虐殺致死。然而，近期的部分研究報告與官方紀錄（如保密局檔案）中，僅記載其死因為「因頭部受鈍器重擊導致腦出血」，未詳述醫院內的殘酷虐殺過程。評論者因此強烈抨擊，認為當前的轉型正義論述刻意「淡化」了外省公務員遭暴民殘殺的史實，且劉青山之家屬未能獲得二二八基金會的任何賠償與名譽回復，是極端的不公不義。''': '''Liu Qing-shan was a 28-year-old Mainlander civil servant at the Monopoly Bureau's Taichung Branch during the 228 Incident. On March 2, 1947, when angry Taichung crowds surrounded the residence of former Taichung County Magistrate Liu Cun-zhong in protest, Liu Qing-shan rushed out and fired at the crowd, injuring several protesters. This provoked extreme outrage from the crowd, who immediately surrounded and severely beat him. According to some official archives and eyewitness records, after he was hospitalized, rioters allegedly stormed his ward on the night of March 3, cutting off his ears and nose, gouging out his eyes, and brutally murdering him. However, recent research reports and official records (such as the Secrecy Bureau archives) only state his cause of death as "cerebral hemorrhage due to severe blunt force trauma to the head," without detailing the brutal torture. Commentators violently attack this, believing the current transitional justice narrative deliberately "downplays" the historical truth of a Mainlander civil servant slain by a mob, and that his family received no compensation or rehabilitation from the 228 Foundation, deeming it extremely unjust.''',

    '''形成強烈對比的是本省籍人士何鑾旗。在事件當時，憲兵第四團曾指控何鑾旗「帶領群眾毆打外省人」，甚至具體指控他「親手殺害專賣局官員莊青山（即劉青山之誤植）」。然而，該案經過當時的台灣高等法院審理後，於1948年因「證據不足」判決何鑾旗涉犯內亂罪嫌疑部分無罪。不幸的是，何鑾旗在隔年（1949年）因捲入其他債務糾紛，被警備總部羅織「恐嚇、詐欺、擾亂金融、煽動流氓、圖謀不軌」等罪名，由中部戒嚴司令部判處死刑並於同年8月執行槍決。儘管何鑾旗的死刑執行時間為1949年，且表面罪名與二二八抗爭無直接關聯，但二二八事件紀念基金會於1997年的第21次董事會中，經過嚴密調查，認定其後續遭到羅織罪名與剝奪生命，實為二二八事件後續威權政府秋後算帳與「公權力侵害」的延伸，因此決議認定其為二二八事件受難者並給予賠償；2023年，法務部更進一步公告平復其所受之司法與行政不法。''': '''Forming a sharp contrast is Taiwanese citizen He Luan-qi. At the time of the incident, the 4th Military Police Regiment accused He Luan-qi of "leading a mob to beat Mainlanders" and even specifically "personally murdering Monopoly Bureau official Zhuang Qing-shan (a misnomer for Liu Qing-shan)." However, after being tried by the Taiwan High Court, he was acquitted in 1948 of suspected rebellion due to "insufficient evidence." Unfortunately, the following year (1949), after getting entangled in other debt disputes, the Garrison Command framed He Luan-qi for "intimidation, fraud, disrupting finance, inciting hooligans, and plotting treason." The Central Martial Law Command sentenced him to death, executing him in August that year. Even though his execution occurred in 1949 and his ostensible charges weren't directly linked to the 228 resistance, the Memorial Foundation of 228, through rigorous investigation, determined that his subsequent framing and execution were an extension of the authoritarian government's settling of scores and "infringement by public power" following the 228 Incident. Thus, they recognized him as a 228 victim and granted compensation. In 2023, the Ministry of Justice further announced the exoneration of his judicial and administrative injustices.''',

    '''上述兩個極端案例的強烈對比，在缺乏法學素養的網路論壇中，極易被操弄為「民進黨政府只賠償本省暴民，卻不顧外省被害公務員」的政治煽動素材。然而，若我們回歸《二二八事件處理及賠償條例》的立法精神與法理基礎進行深度剖析，便會發現這種待遇的差異並非出自所謂的族群偏見，而是源於對「權力結構」與「不法主體」的嚴格法律定義。''': '''This stark contrast between two extreme cases, within online forums lacking legal literacy, is easily manipulated into political incitement material claiming "the DPP government only compensates Taiwanese rioters while ignoring victimized Mainlander civil servants." However, if we return to the legislative spirit and jurisprudential foundation of the "228 Incident Disposition and Compensation Act" for an in-depth analysis, we will find that this difference in treatment does not stem from alleged ethnic bias but from strict legal definitions of "power structure" and "illegal subjects." ''',
    '''轉型正義（Transitional''': '''Transitional justice (''',
    '''Justice）在國際法與政治學上的核心要旨，在於處理「國家機器濫用公權力」所造成的系統性、大規模人權侵害。國家在現代憲政體制下，合法壟斷了暴力的使用權（包括警察、軍隊、情治單位與司法審判權）。當一個威權國家將這些強大的權力武器化，用以非法逮捕、屠殺、刑求其統治下的人民時，人民在體制內是絕對弱勢且缺乏任何救濟管道的。因此，當國家步入民主化後，後繼的民主政府必須承擔起調查真相、賠償受害者與平反名譽的歷史與法律責任。依據《條例》第七條與第八條之明文規定，受難者得受賠償之範圍雖然廣泛，但其最核心的法理前提在於：受害者的損害必須是「遭受公務員及公權力侵害」所致。''': '''Transitional Justice) centers globally in international law and political science on addressing systematic, large-scale human rights violations caused by the "state apparatus abusing public power." Modern constitutional states legitimately monopolize the use of violence (including police, military, intelligence agencies, and judicial powers). When an authoritarian state weaponizes these formidable powers to illegally arrest, massacre, and torture its people, the people are absolutely marginalized with no avenues for recourse within the system. Therefore, when a state democratizes, the successor democratic government must assume the historical and legal responsibility to investigate the truth, compensate victims, and rehabilitate their reputations. According to Articles 7 and 8 of the Act, although the scope of compensable damage is broad, its core jurisprudential premise is: the victim's injury must be caused by "infringement by civil servants and public power." ''',

    # Chapter 4
    '''在二二八事件的歷史詮釋權爭奪戰中，不僅台灣內部存在著不同政治光譜的爭辯，中國共產黨（中共）的強力介入與史觀建構，更為當代的數位認知作戰增添了極為複雜的跨國界層次。近年來，中共官方頻繁且高調地舉辦二二八事件紀念活動，其國台辦發言人甚至公開將二二八事件定調為「台灣同彰反抗專制統治、爭取基本權利的正義行動，亦是中國人民解放鬥爭的一部分」，企圖將台灣民間的自發性民主抗爭，強行收編為中共近代共產革命史觀的一環。''': '''In the battle over the historical interpretative rights of the 228 Incident, not only do debates span different political spectrums within Taiwan, but the strong intervention and historiography construction by the Chinese Communist Party (CCP) have added highly complex transnational dimensions to contemporary digital cognitive warfare. In recent years, CCP officials have frequently and high-profilely held 228 Incident commemorative events. Their Taiwan Affairs Office spokesperson even publicly defined the 228 Incident as "a righteous action by Taiwan compatriots resisting autocratic rule and fighting for basic rights, which is also a part of the Chinese people's liberation struggle," attempting to forcibly co-opt Taiwan's spontaneous civilian democratic resistance into the CCP's modern communist revolution historiography.''',
    '''在中共高調紀念二二八事件的政治宣傳中，經常被抬上檯面的指標性歷史人物是早期台灣共產黨領導人「謝雪紅」。在中共的論述體系中，謝雪紅甚至曾登上天安門城樓與毛澤東並肩，被塑造成二二八事件的絕對領導核心。史料顯示，謝雪紅早年曾赴中國上海與蘇俄學習左翼思想，於1928年參與成立台灣共產黨，並在戰後於台中組織左翼團體。當二二八事件蔓延至中部時，她確實參與了台中武裝民兵「二七部隊」的運作。然而，權威的歷史學界研究對於中共刻意誇大謝雪紅與共產黨在二二八事件中影響力的行為，提出了極為有力的實證反駁。中央研究院近代史副研究員陳儀深指出，謝雪紅作為台共人士且與中共地下黨有聯繫，其在史料研究上固然具有重要性；但在1947年的歷史時空背景下，台灣共產黨員的人數極為稀少，根本不具備在全台性的大規模抗爭中發揮「領導作用」的組織量能。''': '''In the CCP's high-profile political propaganda commemorating the 228 Incident, the iconic historical figure frequently brought to the table is the early Taiwanese Communist Party leader, Xie Xue-hong. In the CCP's narrative system, Xie Xue-hong—who even stood on the Tiananmen rostrum alongside Mao Zedong—is molded into the absolute core leader of the 228 Incident. Historical archives show Xie studied leftist ideology in Shanghai and Soviet Russia early on, partook in founding the Taiwanese Communist Party in 1928, and organized leftist groups in Taichung post-war. When the 228 Incident spread to central Taiwan, she indeed participated in the Taichung armed militia, the "27 Brigade." However, authoritative academic historical research posits extremely robust empirical rebuttals to the CCP's deliberate exaggeration of Xie and the Communist Party's influence in the 228 Incident. Academia Sinica Modern History Associate Research Fellow Chen Yi-shen points out that while Xie, as a Taiwanese Communist affiliated with the CCP underground party, holds historiographical significance, in the 1947 context, Taiwanese Communist members were extremely scarce. They fundamentally lacked the organizational capacity to exert a "leadership role" in an island-wide, large-scale resistance.''',
    '''深入探討這段歷史詮釋的演變，可以發現一個極具諷刺意味的政治現象。誠如《二二八事件真相與轉型正義研究報告》第一篇所探討的「應對路線」分析，當時台灣民間在「處理委員會的體制內改革」與「武裝抵抗」之間掙扎，其核心動能始終是基於對貪腐政治的絕望與對民主自治的渴望。然而，在1947年事件當下，威權體制下的國民黨軍政高層（如陳儀等人），為了合理化其調動中央大軍來台進行無差別屠殺的正當性，刻意向蔣中正極力誇大「中共奸匪在台煽動叛亂」的虛假威脅；而到了數十年後的今日，中國共產黨為了統戰台灣的政治需求、形塑「兩岸革命同源、共同反抗國民黨」的歷史論述，竟然同樣選擇極力膨脹共產黨在二二八事件中的影響力。''': '''Delving into the evolution of this historical interpretation reveals a highly ironic political phenomenon. As discussed in the "Response Approaches" analysis in Chapter 1 of the "Research Report on the Truth of the 228 Incident and Transitional Justice," Taiwanese civilians struggled between the Settlement Committee's "intra-system reform" and "armed resistance"; the core momentum was always based on despair toward political corruption and a thirst for democratic autonomy. Yet, during the 1947 event, to rationalize the legitimacy of mobilizing massive central forces to massacre people indiscriminately, high-ranking military and political KMT officials under the authoritarian regime (such as Chen Yi) deliberately exaggerated the false threat of "Communist bandits inciting rebellion in Taiwan" to Chiang Kai-shek. Fast forward decades to today, to meet the political needs of its united front work against Taiwan and shape the historical narrative that "the revolutions on both sides originate from the same source, jointly resisting the KMT," the CCP paradoxically also chooses to forcefully inflate the Communist Party's influence in the 228 Incident.''',

    # Chapter 5
    '''回歸本報告之初所面臨的核心命題：「近期網路帳號不斷發送影片，攻擊民進黨在操弄二二八」，我們必須將這種現象置於當代數位資訊戰、演算法擴散與假訊息傳播的框架下進行嚴肅檢視。這類攻擊的典型特徵在於：巧妙地將部分真實的歷史細節或個人背景，與大量虛構的數據、扭曲的法理概念進行縫合，藉由煽動群眾的情緒與剝奪感，來徹底摧毀官方轉型正義機構的公信力。''': '''Returning to the core proposition faced at the beginning of this report: "Recent internet accounts continuously dispatch videos attacking the DPP for manipulating 228," we must strictly examine this phenomenon within the framework of contemporary digital information warfare, algorithmic diffusion, and disinformation propagation. The typical characteristic of such attacks lies in cleverly stitching together partial genuine historical details or personal backgrounds with vast amounts of fabricated data and distorted jurisprudential concepts. By inciting mass emotions and a sense of deprivation, they aim to completely destroy the credibility of official transitional justice institutions.''',

    # Chapter 6
    '''綜合上述針對二二八事件歷史論述、傷亡數據實證、轉型正義法理基礎以及當代資訊戰運作機制的全面性探討，本報告得出以下具體結論：''': '''Synthesizing the above comprehensive discussion regarding the 228 Incident's historical narratives, casualty data empirical evidence, transitional justice jurisprudential foundation, and contemporary information warfare mechanisms, this report draws the following concrete conclusions:''',
    '''關於網路上頻繁指控「特定政黨或團體刻意操弄二二八事件、捏造數據」的論述，絕大多數是建立在對歷史事實的斷章取義、對法學概念的張冠李戴，乃至於蓄意的數位認知作戰之上。在最受爭議的傷亡數據方面，儘管歷史學界與人口學界對於「宏觀人口推估」的理論模型（如一萬八千人至兩萬八千人之說）確實存在基於流行病學與人口流動變數的學術探討空間；但財團法人二二八事件紀念基金會實際運作的核心，始終是奠基於最嚴格的檔案證據審理。其所核發的''': '''Regarding the frequent online allegations that "specific political parties or groups deliberately manipulate the 228 Incident and fabricate data," the vast majority are built upon the out-of-context quoting of historical facts, the misattribution of legal concepts, and even deliberate digital cognitive warfare. Regarding the most controversial casualty figures, despite the academic exploration space based on epidemiological and population flow variables within historical and demographic circles regarding "macro population projection" theoretical models (such as the 18,000 to 28,000 death toll claim), the core of the Memorial Foundation of 228's actual operation is consistently founded on the strictest evidentiary review of archives. The''',
    '''位受難者賠償名單，是台灣社會法治精神的展現。反觀網路論述刻意引用早期誇大的警政報表，宣稱「外省人死傷遠高於本省人」，已被基金會嚴謹的檔案考據徹底證偽（實證確認外省籍死亡與失蹤人數為89人）。''': '''victims' compensation roster it approved is a demonstration of the rule of law spirit in Taiwanese society. Conversely, the deliberate online invocation of early exaggerated police charts claiming "Mainlander casualties far outnumbered Taiwanese" has been thoroughly debunked by the Foundation’s rigorous archival research (which empirically confirmed 89 Mainlander dead and missing).''',
    '''歷史的真相從不畏懼任何嚴格的科學與法理檢驗，但必須建立在完整的檔案證據、客觀的學術方法與清晰的法理邏輯之上。面對數位時代下層出不窮、手法日益精緻的歷史錯假訊息與認知作戰，社會大眾亟需提升資訊識讀能力，辨識「學術考證」與「政治宣傳」之間的巨大鴻溝。唯有持續正視過去國家暴力的歷史責任，堅定支持基於檔案實證的轉型正義工程，並在法治的基礎上還原歷史全貌，台灣社會方能真正超越歷史遺留的族群與黨派撕裂，抵禦外部與內部的認知操弄，達成實質意義上的歷史和解與民主鞏固。''': '''The truth of history never fears any rigorous scientific and jurisprudential examination, but it must be built upon complete archival evidence, objective academic methods, and clear jurisprudential logic. Facing the endlessly emerging, increasingly sophisticated historical disinformation and cognitive warfare under the digital era, the public urgently needs to elevate information literacy to discern the massive chasm between "academic textual research" and "political propaganda." Only by continuously confronting the historical responsibilities of past state violence, firmly supporting archive-based transitional justice projects, and restoring the full picture of history upon the foundation of the rule of law, can Taiwanese society truly transcend ethnic and partisan tearing left by history, resist external and internal cognitive manipulation, and achieve substantive historical reconciliation and democratic consolidation.''',
}

for k, v in repls.items():
    html = html.replace(k, v)

with open('index_en.html', 'w', encoding='utf-8') as f:
    f.write(html)
